### ISSUE TITLE
demo on custom data

### ISSUE THREAD

**Issue by laubravo** [muelea/buddi#4]
Hi!

Great work! Is there a demo script for running the optimization on custom data? If not could you detail the steps needed?

Thanks

**Comment by muelea** [comment]
Hi laubravo,

we have a new model and the custom data demo is now available in out repo and as Colab: 
https://colab.research.google.com/drive/1P7x2gY_VuFz5yjZHTRfEBzsEmA-JYGlE?usp=sharing#scrollTo=AGHFIqJ_57Z4 

Best,
Lea
