### ISSUE TITLE
🦒 colab

### ISSUE THREAD

**Issue by camenduru** [muelea/buddi#8]
Hi 👋 Thanks for the project ❤ I've created a colab notebook https://github.com/camenduru/buddi-colab 

However, I'm unsure about how to generate vitpose keypoints. Could you please help me with this?

https://raw.githubusercontent.com/muelea/buddi/main/demo/data/FlickrCI3D_Signatures/demo/vitpose/college_232334_keypoints.json

**Comment by muelea** [comment]
Hi camenduru,

thank you so much for setting up the Colab! I am sorry for the delay, I was transitioning between jobs/labs/countries, but finally found time to work on the demo. ViTPose and BEV are integrated in this repo as third-party and the demo script works with custom images. Here is the [Colab](https://colab.research.google.com/drive/1P7x2gY_VuFz5yjZHTRfEBzsEmA-JYGlE?usp=sharing#scrollTo=AGHFIqJ_57Z4).

To get ViTPose full body key points you can use this function: `python llib/utils/keypoints/vitpose_model.py --image_folder demo/data/images_live --out_folder demo/data/vitpose_live `

Usually, ViTPose whole body is good enough such that running OpenPose is not necessary. If you want use OpenPose in addition, pass the OpenPose keypoint folder to the optimization script by changing `datasets.demo.openpose_folder=none` to `datasets.demo.openpose_folder=YOUR_OPENPOSE_FOLDER`.

`python llib/methods/hhcs_optimization/main.py --exp-cfg llib/methods/hhcs_optimization/configs/buddi_cond_bev_demo.yaml --exp-opts logging.base_folder=demo/optimization/buddi_cond_bev_demo_live datasets.train_names=['demo'] datasets.train_composition=[1.0] datasets.demo.original_data_folder=demo/data datasets.demo.image_folder=images_live datasets.demo.bev_folder=bev_live datasets.demo.vitpose_folder=vitpose_live datasets.demo.openpose_folder=none model.optimization.pretrained_diffusion_model_ckpt=essentials/buddi/buddi_cond_bev.pt model.optimization.pretrained_diffusion_model_cfg=essentials/buddi/buddi_cond_bev.yaml logging.run=fit_buddi_cond_bev_flickrci3ds`

**Comment by camenduru** [comment]
Thank you ❤ it is working now 🥳
